from llm.schemas import LLMMessage, LLMRequest
from llm.service import LLMService

from .embeddings import EmbeddingModel
from .retrieval import Retriever
from .schemas import Citation, RAGResponse, deduplicate_citations


class RAGService:
    """
    Application-level service for KARYA Retrieval-Augmented Generation.

    Responsibilities:
        1. Embed the user question.
        2. Retrieve relevant document chunks.
        3. Filter weak retrieval results.
        4. Build grounded context.
        5. Ask the local LLM for ONLY the answer.
        6. Return answer and citations separately.

    IMPORTANT:
        The LLM must never generate source metadata.

        Sources are generated by KARYA from the actual retrieval
        results and returned separately from the answer.
    """

    def __init__(
        self,
        embedding_model: EmbeddingModel | None = None,
        retriever: Retriever | None = None,
        llm_service: LLMService | None = None,
    ):
        self.embedding_model = (
            embedding_model or EmbeddingModel()
        )

        self.retriever = (
            retriever or Retriever()
        )

        self.llm_service = (
            llm_service or LLMService()
        )

    def answer(
        self,
        question: str,
        top_k: int = 3,
        similarity_threshold: float = 0.55,
        document_ids: list[str] | None = None,
    ) -> RAGResponse:
        """
        Answer a question using KARYA's local knowledge base.

        The returned answer contains only natural-language text.

        Citations are returned separately in RAGResponse.citations.
        """

        # ---------------------------------------------------------
        # 1. Validate question
        # ---------------------------------------------------------

        if not question or not question.strip():
            raise ValueError(
                "Question cannot be empty."
            )

        question = question.strip()

        # ---------------------------------------------------------
        # 2. Validate top_k
        # ---------------------------------------------------------

        if top_k <= 0:
            raise ValueError(
                "top_k must be greater than zero."
            )

        # ---------------------------------------------------------
        # 3. Validate similarity threshold
        # ---------------------------------------------------------

        if not 0.0 <= similarity_threshold <= 1.0:
            raise ValueError(
                "similarity_threshold must be between 0.0 and 1.0."
            )

        # ---------------------------------------------------------
        # 4. Create query embedding
        # ---------------------------------------------------------

        query_embedding = self.embedding_model.embed_text(
            question
        )

        # ---------------------------------------------------------
        # 5. Retrieve relevant chunks
        # ---------------------------------------------------------

        results = self.retriever.search(
            query_embedding=query_embedding,
            top_k=top_k,
            document_ids=document_ids,
        )

        # ---------------------------------------------------------
        # 6. Remove weak results
        # ---------------------------------------------------------

        results = [
            result
            for result in results
            if result.similarity >= similarity_threshold
        ]

        # ---------------------------------------------------------
        # 7. No evidence found
        # ---------------------------------------------------------

        if not results:
            return RAGResponse(
                answer=(
                    "I couldn't find sufficient evidence "
                    "in the local knowledge base to answer "
                    "this reliably."
                ),
                citations=[],
            )

        # ---------------------------------------------------------
        # 8. Build LLM context
        # ---------------------------------------------------------

        context_parts: list[str] = []

        for result in results:
            page_info = (
                str(result.page_number)
                if result.page_number is not None
                else "Unknown"
            )

            context_parts.append(
                f"Document: {result.file_name}\n"
                f"Page: {page_info}\n"
                f"Content:\n{result.content}"
            )

        context = "\n\n---\n\n".join(
            context_parts
        )

        # ---------------------------------------------------------
        # 9. Build clean grounding prompt
        # ---------------------------------------------------------

        prompt = f"""
You are KARYA, a sovereign industrial AI assistant.

Your job is to answer the user's question using ONLY the
information contained in the local knowledge-base context.

STRICT RULES:

1. Answer the user's question directly.
2. Use only information supported by the supplied context.
3. Do not invent facts.
4. Do not guess.
5. Do not mention "the context".
6. Do not mention "the knowledge base".
7. Do not say "according to the provided context".
8. Do not generate citations.
9. Do not generate source names.
10. Do not generate page numbers.
11. Do not generate chunk IDs.
12. Do not generate UUIDs.
13. Do not generate similarity scores.
14. Do not add a "Sources" section.
15. Do not repeat the user's question.
16. Keep the answer concise and factual.
17. Return ONLY the answer text.

If the context does not contain enough information to answer
the question, respond exactly with:

I couldn't find sufficient evidence in the local knowledge base to answer this reliably.

LOCAL KNOWLEDGE-BASE CONTEXT:
{context}

USER QUESTION:
{question}

ANSWER:
""".strip()

        # ---------------------------------------------------------
        # 10. Create LLM request
        # ---------------------------------------------------------

        request = LLMRequest(
            messages=[
                LLMMessage(
                    role="system",
                    content=(
                        "You are KARYA, a precise industrial AI "
                        "assistant. Answer only from supplied "
                        "evidence. Return only the direct answer. "
                        "Never generate citations or source metadata."
                    ),
                ),
                LLMMessage(
                    role="user",
                    content=prompt,
                ),
            ],
            temperature=0.1,
        )

        # ---------------------------------------------------------
        # 11. Generate answer
        # ---------------------------------------------------------

        response = self.llm_service.chat(
            request
        )

        answer = self._clean_answer(
            response.content
        )

        # ---------------------------------------------------------
        # 12. Build structured citations
        # ---------------------------------------------------------

        citations = [
            Citation(
                file_name=result.file_name,
                file_type=result.file_type,
                page_number=result.page_number,
                chunk_id=result.chunk_id,
                similarity=result.similarity,
                document_id=result.document_id,
                source_text=result.content,
            )
            for result in results
        ]

        # ---------------------------------------------------------
        # 13. Deduplicate citations
        # ---------------------------------------------------------

        citations = deduplicate_citations(
            citations
        )

        # ---------------------------------------------------------
        # 14. Return clean response
        # ---------------------------------------------------------

        return RAGResponse(
            answer=answer,
            citations=citations,
        )

    @staticmethod
    def _clean_answer(answer: str) -> str:
        """
        Clean accidental formatting generated by the LLM.

        The prompt already instructs the model not to produce
        citations, but this defensive layer protects the UI if
        the local model still adds them.
        """

        if not isinstance(answer, str):
            return ""

        answer = answer.strip()

        if not answer:
            return (
                "I couldn't generate a reliable answer "
                "from the available evidence."
            )

        # Remove markdown fences accidentally returned by a model.
        if answer.startswith("```") and answer.endswith("```"):
            lines = answer.splitlines()

            if len(lines) >= 3:
                answer = "\n".join(
                    lines[1:-1]
                ).strip()

        # Remove accidental "Answer:" prefix.
        prefixes = (
            "Answer:",
            "ANSWER:",
            "Final Answer:",
            "FINAL ANSWER:",
        )

        for prefix in prefixes:
            if answer.startswith(prefix):
                answer = answer[len(prefix):].strip()
                break

        # Remove source/citation blocks if a model ignores
        # the instructions and produces them anyway.
        lines = answer.splitlines()

        cleaned_lines: list[str] = []

        for line in lines:
            stripped = line.strip()

            if stripped.startswith("[Source:"):
                continue

            if stripped.lower().startswith("sources:"):
                break

            cleaned_lines.append(line)

        answer = "\n".join(
            cleaned_lines
        ).strip()

        return answer