"""create sessions table

Revision ID: 0a1eccc25ba3
Revises: 4067925e8448
Create Date: 2026-09-04 18:38:25.725447
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a1eccc25ba3'
down_revision: Union[str, Sequence[str], None] = '4067925e8448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('refresh_token_hash', sa.String(length=128), nullable=False))
    op.add_column('sessions', sa.Column('revoked', sa.Boolean(), nullable=False))
    op.alter_column('sessions', 'user_agent',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('sessions', 'ip_address',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.alter_column('sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('sessions', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_column('sessions', 'last_seen_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('last_seen_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('sessions', 'revoked_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('sessions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('sessions', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('sessions', 'ip_address',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('sessions', 'user_agent',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
    op.drop_column('sessions', 'revoked')
    op.drop_column('sessions', 'refresh_token_hash')
    # ### end Alembic commands ###
