"""add refresh token tracking

Revision ID: cdbd028d2eaa
Revises: 0a1eccc25ba3
Create Date: 2026-09-04 20:37:14.457995
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdbd028d2eaa'
down_revision: Union[str, Sequence[str], None] = '0a1eccc25ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('jti', sa.String(length=36), nullable=False))
    op.add_column('sessions', sa.Column('token_family', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_sessions_jti'), 'sessions', ['jti'], unique=True)
    op.create_index(op.f('ix_sessions_token_family'), 'sessions', ['token_family'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_token_family'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_jti'), table_name='sessions')
    op.drop_column('sessions', 'token_family')
    op.drop_column('sessions', 'jti')
    # ### end Alembic commands ###
