# ============================================================
# AUTH SECURITY
# ============================================================

PASSWORD_MIN_LENGTH: int = 12

BRUTE_FORCE_ATTEMPTS: int = 5
BRUTE_FORCE_WINDOW_SECONDS: int = 900

AUTH_RATE_LIMIT_WINDOW_SECONDS: int = 60

AUTH_REGISTER_RATE_LIMIT: int = 5

AUTH_LOGIN_IP_RATE_LIMIT: int = 30
AUTH_LOGIN_ACCOUNT_RATE_LIMIT: int = 10

AUTH_REFRESH_RATE_LIMIT: int = 30
AUTH_LOGOUT_RATE_LIMIT: int = 30

PASSWORD_RESET_RATE_LIMIT: int = 5
VERIFICATION_RESEND_RATE_LIMIT: int = 3

MFA_RATE_LIMIT_PER_MINUTE: int = 5

# Session security
ACCESS_TOKEN_EXPIRE_MINUTES: int = 15
REFRESH_TOKEN_EXPIRE_DAYS: int = 30

SESSION_IDLE_TIMEOUT_DAYS: int = 7
SESSION_ABSOLUTE_TIMEOUT_DAYS: int = 90